Import('env')

env = env.Clone()

subdirs = ['actions', 'entities', 'shell']

objects = [ obj for subdir in subdirs for objs in env.SConscript('%s/SConscript' % subdir, { 'env': env }) for obj in objs ]

executables = [ env.StaticObject(src) for src in [ 'main.cpp' ] ]

retVal = { 'objects': objects, 'executables': executables }

Return('retVal')
